spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buildmaster?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: asd962464..
    hikari:
      maximum-pool-size: 10  # 最大连接数
      minimum-idle: 5        # 最小空闲连接
      idle-timeout: 300000   # 空闲连接超时时间（毫秒）
      connection-timeout: 20000  # 连接超时时间（毫秒）
#  data:
#    redis:
#      host: localhost
#      port: 6379
